[package]
name = "frontend-api"
version.workspace = true
edition.workspace = true

[dependencies]
domain = { path = "../domain", default-features = false }
domain-snapshot = { path = "../domain-snapshot" }
application = { path = "../application" }
flavor = { path = "../flavor" }
infrastructure = { path = "../infrastructure" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
