[package]
name = "domain"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
ron = "0.8"
mlua = { version = "0.10", features = ["lua54", "send", "vendored"], optional = true }

[features]
default = ["lua"]
lua = ["mlua"]

[dev-dependencies]
serde_json = "1"
