[package]
name = "presentation"
version.workspace = true
edition.workspace = true

[dependencies]
application = { path = "../application" }
domain = { path = "../domain" }
bevy = { version = "0.18", default-features = false, features = [
    "bevy_asset",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "bevy_window",
    "bevy_winit",
    "default_font",
    "x11",
    "multi_threaded",
] }
